<?php
/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:3.35.1|configurator
 * you can change this configuration by importing this file.
 */
$config = new PhpCsFixer\Config();
return $config
	->setRiskyAllowed(true)
	->setIndent("\t")
	->setRules([
		'align_multiline_comment' => true,
		'array_indentation' => true,
		'array_push' => true,
		'array_syntax' => true,
		'assign_null_coalescing_to_coalesce_equal' => true,
		'attribute_empty_parentheses' => true,
		'backtick_to_shell_exec' => true,
		'binary_operator_spaces' => true,
		'blank_line_after_namespace' => true,
		'blank_lines_before_namespace' => ['max_line_breaks' => 0, 'min_line_breaks' => 0],
		'braces_position' => ['classes_opening_brace' => 'same_line', 'functions_opening_brace' => 'same_line'],
		'cast_spaces' => ['space' => 'single'],
		'class_attributes_separation' => ['elements' => ['method' => 'one']],
		'class_definition' => ['multi_line_extends_each_single_line' => false, 'single_item_single_line' => true, 'single_line' => true],
		'class_reference_name_casing' => true,
		'clean_namespace' => true,
		'combine_consecutive_issets' => true,
		'combine_consecutive_unsets' => true,
		'combine_nested_dirname' => true,
		'comment_to_phpdoc' => true,
		'compact_nullable_type_declaration' => true,
		'concat_space' => ['spacing' => 'one'],
		'constant_case' => true,
		'control_structure_braces' => true,
		'control_structure_continuation_position' => true,
		'date_time_create_from_format_call' => true,
		'date_time_immutable' => true,
		'declare_equal_normalize' => ['space' => 'single'],
		'declare_parentheses' => true,
		'dir_constant' => true,
		'echo_tag_syntax' => ['shorten_simple_statements_only' => false],
		'empty_loop_body' => true,
		'empty_loop_condition' => true,
		'encoding' => true,
		'ereg_to_preg' => true,
		'escape_implicit_backslashes' => ['single_quoted' => false, 'double_quoted' => true, 'heredoc_syntax' => true],
		'explicit_indirect_variable' => true,
		'explicit_string_variable' => true,
		'full_opening_tag' => true,
		'fully_qualified_strict_types' => true,
		'function_declaration' => true,
		'function_to_constant' => true,
		'get_class_to_class_keyword' => true,
		'global_namespace_import' => true,
		'heredoc_to_nowdoc' => true,
		'implode_call' => true,
		'include' => true,
		'increment_style' => ['style' => 'post'],
		'indentation_type' => true,
		'integer_literal_case' => true,
		'is_null' => true,
		'lambda_not_used_import' => true,
		'line_ending' => true,
		'list_syntax' => ['syntax' => 'short'],
		'logical_operators' => true,
		'long_to_shorthand_operator' => true,
		'lowercase_cast' => true,
		'lowercase_keywords' => true,
		'lowercase_static_reference' => true,
		'magic_constant_casing' => true,
		'magic_method_casing' => true,
		'mb_str_functions' => true,
		'method_argument_space' => ['keep_multiple_spaces_after_comma' => false, 'on_multiline' => 'ensure_fully_multiline'],
		'method_chaining_indentation' => true,
		'modernize_strpos' => true,
		'modernize_types_casting' => true,
		'multiline_whitespace_before_semicolons' => true,
		'native_constant_invocation' => true,
		'native_function_casing' => true,
		'native_type_declaration_casing' => true,
		'new_with_parentheses' => true,
		'no_alias_functions' => true,
		'no_alias_language_construct_call' => true,
		'no_alternative_syntax' => true,
		'no_binary_string' => true,
		'no_blank_lines_after_class_opening' => true,
		'no_blank_lines_after_phpdoc' => true,
		'no_closing_tag' => true,
		'no_empty_comment' => true,
		'no_empty_phpdoc' => true,
		'no_empty_statement' => true,
		'no_extra_blank_lines' => ['tokens' => ['break', 'case', 'continue', 'curly_brace_block', 'default', 'extra', 'parenthesis_brace_block', 'return', 'square_brace_block', 'switch', 'throw', 'use']],
		'no_homoglyph_names' => true,
		'no_leading_import_slash' => true,
		'no_leading_namespace_whitespace' => true,
		'no_mixed_echo_print' => true,
		'no_multiline_whitespace_around_double_arrow' => true,
		'no_multiple_statements_per_line' => true,
		'no_null_property_initialization' => true,
		'no_php4_constructor' => true,
		'no_short_bool_cast' => true,
		'no_singleline_whitespace_before_semicolons' => true,
		'no_space_around_double_colon' => true,
		'no_spaces_after_function_name' => true,
		'no_spaces_around_offset' => true,
		'no_superfluous_elseif' => true,
		'no_trailing_comma_in_singleline' => true,
		'no_trailing_whitespace' => true,
		'no_trailing_whitespace_in_comment' => true,
		'no_trailing_whitespace_in_string' => true,
		'no_unneeded_braces' => true,
		'no_unneeded_control_parentheses' => true,
		'no_unneeded_final_method' => true,
		'no_unneeded_import_alias' => true,
		'no_unreachable_default_argument_value' => true,
		'no_unset_cast' => true,
		'no_unset_on_property' => true,
		'no_unused_imports' => true,
		'no_useless_concat_operator' => true,
		'no_useless_else' => true,
		'no_useless_nullsafe_operator' => true,
		'no_useless_return' => true,
		'no_useless_sprintf' => true,
		'no_whitespace_before_comma_in_array' => true,
		'no_whitespace_in_blank_line' => true,
		'non_printable_character' => true,
		'normalize_index_brace' => true,
		'nullable_type_declaration' => true,
		'nullable_type_declaration_for_default_null_value' => true,
		'object_operator_without_whitespace' => true,
		'operator_linebreak' => true,
		'ordered_class_elements' => ['order' => ['use_trait', 'constant', 'property', 'construct', 'destruct', 'magic']],
		'ordered_imports' => ['sort_algorithm' => 'length'],
		'ordered_interfaces' => true,
		'ordered_traits' => true,
		'php_unit_construct' => true,
		'php_unit_data_provider_return_type' => true,
		'php_unit_data_provider_static' => ['force' => true],
		'php_unit_dedicate_assert' => true,
		'php_unit_dedicate_assert_internal_type' => true,
		'php_unit_expectation' => true,
		'php_unit_method_casing' => ['case' => 'snake_case'],
		'php_unit_mock' => true,
		'php_unit_mock_short_will_return' => true,
		'php_unit_namespaced' => true,
		'php_unit_no_expectation_annotation' => true,
		'php_unit_set_up_tear_down_visibility' => true,
		'php_unit_test_annotation' => ['style' => 'annotation'],
		'php_unit_test_case_static_method_calls' => ['call_type' => 'this'],
		'phpdoc_align' => true,
		'phpdoc_annotation_without_dot' => true,
		'phpdoc_indent' => true,
		'phpdoc_inline_tag_normalizer' => true,
		'phpdoc_no_access' => true,
		'phpdoc_no_alias_tag' => true,
		'phpdoc_no_empty_return' => true,
		'phpdoc_no_package' => true,
		'phpdoc_no_useless_inheritdoc' => true,
		'phpdoc_order' => true,
		'phpdoc_order_by_value' => true,
		'phpdoc_readonly_class_comment_to_keyword' => true,
		'phpdoc_return_self_reference' => true,
		'phpdoc_scalar' => true,
		'phpdoc_separation' => true,
		'phpdoc_single_line_var_spacing' => true,
		'phpdoc_summary' => true,
		'phpdoc_tag_casing' => true,
		'phpdoc_tag_type' => true,
		'phpdoc_to_comment' => true,
		'phpdoc_to_param_type' => true,
		'phpdoc_trim' => true,
		'phpdoc_trim_consecutive_blank_line_separation' => true,
		'phpdoc_types' => true,
		'phpdoc_types_order' => ['null_adjustment' => 'always_last'],
		'phpdoc_var_annotation_correct_order' => true,
		'phpdoc_var_without_name' => true,
		'pow_to_exponentiation' => true,
		'psr_autoloading' => true,
		'random_api_migration' => true,
		'regular_callable_call' => true,
		'return_assignment' => true,
		'return_to_yield_from' => true,
		'return_type_declaration' => true,
		'self_accessor' => true,
		'self_static_accessor' => true,
		'semicolon_after_instruction' => true,
		'set_type_to_cast' => true,
		'short_scalar_cast' => true,
		'simple_to_complex_string_variable' => true,
		'simplified_null_return' => true,
		'single_blank_line_at_eof' => true,
		'single_class_element_per_statement' => true,
		'single_import_per_statement' => true,
		'single_line_after_imports' => true,
		'single_line_comment_style' => true,
		'single_quote' => true,
		'single_space_around_construct' => true,
		'space_after_semicolon' => true,
		'spaces_inside_parentheses' => true,
		'standardize_increment' => true,
		'standardize_not_equals' => true,
		'statement_indentation' => true,
		'strict_comparison' => true,
		'strict_param' => true,
		'string_length_to_empty' => true,
		'string_line_ending' => true,
		'switch_case_semicolon_to_colon' => true,
		'switch_case_space' => true,
		'switch_continue_to_break' => true,
		'ternary_operator_spaces' => true,
		'ternary_to_elvis_operator' => true,
		'ternary_to_null_coalescing' => true,
		'trailing_comma_in_multiline' => true,
		'trim_array_spaces' => true,
		'type_declaration_spaces' => true,
		'types_spaces' => true,
		'unary_operator_spaces' => true,
		'use_arrow_functions' => true,
		'visibility_required' => true,
		'whitespace_after_comma_in_array' => true,
		'yield_from_array_to_yields' => true,
	])
	->setFinder(
		PhpCsFixer\Finder::create()
			->exclude('vendor')
			->in(__DIR__)
	);
